server:
  port: 7000
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.118.90:8848
feign:
  client:
    config:
      default:
        # 日志等级
        logger-level: full
        # 超时时间
        connect-timeout: 6000
        read-timeout: 6000
  # 断路器
  circuitbreaker:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
